### ISSUE TITLE
Despliegue de instancia remota de SonarQube

### ISSUE THREAD

**Issue by ags0103** [ags0103/GESPRO_Practicas#13]
Despliegue de una instancia remota de la herramienta SonarQube en la plataforma de OpenShift. Para el despliegue se utilizarán las herramientas de cliente que proporciona OpenShift (ver enlace)

**Comment by tomasyanez3** [comment]
revisado, todo correcto.

**Comment by ags0103** [comment]
Ok, cierro la tarea entonces
