### ISSUE TITLE
Widget de presentación para la instancia de SonarQube

### ISSUE THREAD

**Issue by tomasyanez3** [ags0103/GESPRO_Practicas#18]
Crear un widget que presente información acerca de la plataforma actual de evaluación de trabajos fin de grado.

**Comment by tomasyanez3** [comment]
revisado

**Comment by ags0103** [comment]
Issue  was marked as a duplicate of this issue.

**Comment by tomasyanez3** [comment]
Instalado y configurado widget de presentación en la plataforma actual de evaluación de TFG
