### ISSUE TITLE
Calcular información estadística y configurar un Quality Gate para SonarQube

### ISSUE THREAD

**Issue by ags0103** [ags0103/GESPRO_Practicas#26]
Calcular la información estadística correspondiente a los percentiles 1 y 3 de un conjunto de métricas obtenidas con SonarQube y configurar un Quality Gate con los valores obtenidos.

**Comment by tomasyanez3** [comment]
revisado

**Comment by ags0103** [comment]
ok, perfecto, paso a cerrarlo
