### ISSUE TITLE
 Manual de instalación de SonarQube

### ISSUE THREAD

**Issue by ags0103** [ags0103/GESPRO_Practicas#27]
Anexo de la memoria En Open shift En Local

**Comment by tomasyanez3** [comment]
Revisión de manual de usuario. Complementarla con la entregada en papel.

**Comment by ags0103** [comment]
Manual realizado, comprueba si esta bien la parte de referencias.

**Comment by tomasyanez3** [comment]
todo correcto, revisado.

**Comment by ags0103** [comment]
Perfecto, lo cierro
